### ISSUE TITLE
State of charge not visible in HA - android Phone connection

### ISSUE THREAD

**Issue by BlueForrest** [ReneNulschDE/ha-mysmartbike#3]
Hi,

Thanks for this integration.

Installed the mysmartbike app on my android phone and connected my foldable E-bike (Legend Siena)
That's all working fine.

After installation to HA, I only see 2 entities: 
 - Device Tracker with GPS data
 - Odometer  

The "State of charge (Percent, 0-100)" is not visible as an entity

Is there something I need to change in the app or HA to get this visible?
HA is on the latest May 2024.5 release

  "integration_manifest": {
    "domain": "mysmartbike",
    "name": "MySmartBike",
    "codeowners": [
      "@ReneNulschDE"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/ReneNulschDE/ha-mysmartbike",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/ReneNulschDE/ha-mysmartbike/issues",
    "requirements": [],
    "version": "v0.2.0",
    "is_built_in": false
  },
  "data": {
    "config_entry_data": {
      "username": "**REDACTED**",
      "password": "**REDACTED**"
    },
    "coordinator_data": {
      "LE0000XXXXXXXXXX": {
        "serial": "LE0000XXXXXXXXXX",
        "odometry": 26400,
        "manufacturer_name": "Legend",
        "model_name": "Siena Trio",
        "longitude": -0.000000,
        "latitude": 00.00000,
        "last_position_date": "2024-05-04T13:20:18",
        "state_of_charge": null,
        "remaining_capacity": null

note: serial, long & lat have been modified

Thanks for checking.

**Comment by ReneNulschDE** [comment]
Thanks for opening the issue. Looks like my routine to collect the state of charge does not work for your bike. You can help me to fix it...

Please use a browser and go to: https://my-smartbike.com/
Login with the same credentials like in Home Assistant. 
Go to the "My ebikes" on the left side.
Open the Developer Tools of the browser, go to Network tab and refresh the page.
You will see all the different requests in the network tab. We are interested on the request to "me"-endpoint and especially the request to `/api/v1/objects/me`. 
Please send the response of this request to MySmartBike.i3@nulsch.de and I will check the soc issue.

Thanks again. Best René

**Comment by ReneNulschDE** [comment]
As discussed via email: The MySmartBike portal has no information about the state of charge for this bike. Looks like not all components are from Mahle.

Will close the issue.
