### ISSUE TITLE
odometry error on Home Assistant Integration

### ISSUE THREAD

**Issue by BlueForrest** [ReneNulschDE/ha-mysmartbike#6]
Hi, 
Using Mahle integration on HA - Version 0.31.

HA keeps asking me to provide my user details, but when I do, i'm getting an error.
has to do with the odometry.

Below the HA log data.  Hope you can help.   Thanks

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.mysmartbike.coordinator
Bron: helpers/update_coordinator.py:354
integratie: MySmartBike (documentatie, problemen)
Eerst voorgekomen: 8 september 2024 om 23:45:27 (430 gebeurtenissen)
Laatst gelogd: 15:15:32

Unexpected error fetching mysmartbike data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mysmartbike/coordinator.py", line 71, in _async_update_data
    devices = await self.webapi.get_device_list()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mysmartbike/webapi.py", line 112, in get_device_list
    return await self._build_device_list(_response, _location_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mysmartbike/webapi.py", line 198, in _build_device_list
    rbike["odometry"],
    ~~~~~^^^^^^^^^^^^
KeyError: 'odometry'

**Comment by ReneNulschDE** [comment]
Thanks for reporting the issue. Please enable the debug log on the integration page (or enable it via the configuration.yaml see [here](https://github.com/ReneNulschDE/ha-mysmartbike?tab=readme-ov-file#logging))
<img width="327" alt="image" src="https://github.com/user-attachments/assets/ca5b35fa-726f-4106-bb31-4de816936146">
Try again and share the log output. The debug log will include the server response.
Thx

**Comment by BlueForrest** [comment]
Hi, Enabled debug logging, see result below:

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.mysmartbike.coordinator
Bron: helpers/update_coordinator.py:354
integratie: MySmartBike (documentatie, problemen)
Eerst voorgekomen: 8 september 2024 om 23:45:27 (800 gebeurtenissen)
Laatst gelogd: 23:21:21

Unexpected error fetching mysmartbike data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mysmartbike/coordinator.py", line 71, in _async_update_data
    devices = await self.webapi.get_device_list()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mysmartbike/webapi.py", line 112, in get_device_list
    return await self._build_device_list(_response, _location_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mysmartbike/webapi.py", line 198, in _build_device_list
    rbike["odometry"],
    ~~~~~^^^^^^^^^^^^
KeyError: 'odometry'

**Comment by ReneNulschDE** [comment]
Unfortunately, this just the error and not the debug log. Please check the homeassistant.log (Settings, System, log —> klick on Load full log at the bottom of the page) and share all lines with mysmartbike.

**Comment by BlueForrest** [comment]
Hi, sorry for this (i'm not so familiar with these log messages, but thanks for pointing me how to filter.
Annex log file. Hope this helps
[home-assistant_2024-09-10T19-27-38.696Z.log](https://github.com/user-attachments/files/16949965/home-assistant_2024-09-10T19-27-38.696Z.log)

**Comment by ReneNulschDE** [comment]
Thanks for the log. I have to adjust the code a litte bit to get the right debug output. I'll deploy a new version over the weekend.

**Comment by ReneNulschDE** [comment]
I have published a version 0.3.2 - Please install, enable the debug log and share it again. The exception should not happen anymore but the odo will be -1 . With the log output I can check if there is chance to get the odo information in a different way for your bike.

**Comment by BlueForrest** [comment]
Hi Rene,

Finally had the the time to install your new version.

This is the only message from te log:

2024-09-14 10:16:19.850 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration mysmartbike which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

-------------------------------------------

I must inform you that I have two smartbikes registered on my account.
both of them showing up correctly, had no error or issue

so for now it seems to look OK.

**Comment by BlueForrest** [comment]
but here is a more detailed log file 

[home-assistant_2024-09-14T08-51-46.047Z.log](https://github.com/user-attachments/files/17001658/home-assistant_2024-09-14T08-51-46.047Z.log)

**Comment by ReneNulschDE** [comment]
Ok, thanks - looks like that there is no odometry information available for "Legend Siena Marijke". I'll close the issue as the rest looks good. Feel free to reopen and don't forget to disable the debug mode 😄

**Comment by BlueForrest** [comment]
Hi, Yes all is working fine now.  Thanks
